### ISSUE TITLE
Doesn't work with react 0.13 ?

### ISSUE THREAD

**Issue by suryagaddipati** [acdlite/flummox#28]
``npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
   npm ERR! peerinvalid Peer flummox@2.7.0 wants react@0.12.x``

on the features page of the project 

`Support for plain JavaScript class components in React 0.13.`

**Comment by acdlite** [comment]
Ah! My bad. Fixed in 2.7.1

**Comment by suryagaddipati** [comment]
Perfect @acdlite . Thank you.

**Comment by suryagaddipati** [comment]
@acdlite I still get this error

``npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer flummox@2.7.1 wants react@>=0.12.0 ``

My `package.json` is 

``"dependencies": {
    "react": "0.13.0-beta.1",
    "jquery": "latest",
    "flummox": "latest"
  }``

**Comment by acdlite** [comment]
@suryagaddipati D'oh. My bad again. You want 2.7.2. I just removed the peer dependency for now.

**Comment by suryagaddipati** [comment]
``version not found: flummox@2.7.2`` . 

Just wait a while i guess?

**Comment by acdlite** [comment]
Hmm I just checked, should be up. Maybe clear your npm cache?

**Comment by suryagaddipati** [comment]
@acdlite that fixed it. Thank you for your quick response.

**Comment by acdlite** [comment]
No problem. Thanks for catching this.
